(div ()
     (ul ()
     (li  () (a (:href "https://github.com/gabydd/site") "This site"))
     (li  () (a (:href "https://github.com/gabydd/wraith") "Wraith: ") "Wayland only client for Ghostty")
     (li  () (a (:href "https://github.com/gabydd/zig-os") "zig-os: ") "a small kernel for experimenting with the zig riscv backend")
     (li  () (a (:href "https://github.com/gabydd/polaris") "Polaris: ") "Scouting Site for FIRST Robotics")
     (li  () (a (:href "https://github.com/gabydd/await-components") "Await Components: ") "an experiment with a web framework that allows the use of async await")
     (li  () (a (:href "https://github.com/gabydd/fuzzytext") "fuzzytext: ") "a work in progress text renderer in zig only renders outlines at the moment")))
