(defmacro conc-str (&rest body)
  `(concatenate 'string ,@body))

(defun attrs (attributes)
  (if attributes (conc-str " " (string-downcase (symbol-name (car attributes))) "=\"" (cadr attributes) "\"" (attrs (cddr attributes))) ""))

(defmacro element (el)
  `(defmacro ,el (attributes &rest children)
     `(conc-str "<" ,,(string-downcase (symbol-name el)) (attrs (list ,@attributes)) ">" ,@children "</" ,,(string-downcase (symbol-name el)) ">")))

(defun write-html (html file-name)
  (with-open-file (file (conc-str "serve/" file-name ".html") :direction :output :if-exists :supersede)
    (write-string html file)))

(defmacro dohtml ((var list) &body body)
  (let ((binds (gensym)))
    `(apply #'concatenate (let ((,binds (list 'string)))
                            (dolist (,var ,list (nreverse ,binds))
                              (push ,@body ,binds))))))

(element a)
(element abbr)
(element address)
(element area)
(element article)
(element aside)
(element audio)
(element b)
(element bdi)
(element bdo)
(element blockquote)
(element body)
(element br)
(element button)
(element canvas)
(element caption)
(element cite)
(element code)
(element col)
(element colgroup)
(element command)
(element datalist)
(element dd)
(element del)
(element details)
(element dfn)
(element div)
(element dl)
(element dt)
(element em)
(element embed)
(element fieldset)
(element figcaption)
(element figure)
(element footer)
(element form)
(element h1)
(element h2)
(element h3)
(element h4)
(element h5)
(element h6)
(element head)
(element header)
(element hr)
(element html)
(element i)
(element iframe)
(element img)
(element input)
(element ins)
(element kbd)
(element keygen)
(element label)
(element legend)
(element li)
(element link)
(element main)
(element mark)
(element menu)
(element meta)
(element meter)
(element nav)
(element object)
(element ol)
(element optgroup)
(element option)
(element output)
(element p)
(element param)
(element pre)
(element progress)
(element q)
(element rp)
(element rt)
(element ruby)
(element s)
(element samp)
(element section)
(element select)
(element small)
(element source)
(element span)
(element strong)
(element sub)
(element summary)
(element sup)
(element table)
(element tbody)
(element td)
(element textarea)
(element tfoot)
(element th)
(element thead)
(element tr)
(element track)
(element title)
(element u)
(element ul)
(element video)
(element wbr)
